development:
  adapter: postgresql
  database: littlegidding
  pool: 5
  min_messages: warning
  allow_concurrency: true
  timeout: 5000

test:
  adapter: postgresql
  database: littlegidding_test
  pool: 5
  min_messages: warning
  allow_concurrency: true
  timeout: 5000

production:
  adapter: postgresql
  database: littlegidding
  pool: 5
  min_messages: warning
  allow_concurrency: true
  timeout: 5000
